### ISSUE TITLE
SCTP is unsupported on darwin/amd64

### ISSUE THREAD

**Issue by fishlinghu** [ishidawataru/sctp#20]
Hi,

Thank you for creating this library. 
When running the example on my Macbook Pro, I got the following error message: 
"failed to listen: SCTP is unsupported on darwin/amd64"
There is no related information on the Internet. 
Do you have any idea what might be the cause?
I think lots of people are using Macbook, too.

**Comment by ishidawataru** [comment]
Mac OS doesn't have SCTP support natively.

looks like there is a module for it. but not sure it works or not.

https://github.com/sctplab/SCTP_NKE_ElCapitan
