### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by onlyjob** [ishidawataru/sctp#23]
There are two licenses in this project but one can not tell which one applies to which file.
Please document scope of the license, ideally by adding relevant header to each file (to avoid any doubts).

Also I could not find copyright statement... Please add copyright statement to README and to each file's header (unless all files are under the same license).

Thanks.

**Comment by onlyjob** [comment]
Please clarify licensing.

**Comment by ishidawataru** [comment]
fixed by #34

**Comment by onlyjob** [comment]
Thank you.
