### ISSUE TITLE
Incorrect order byte for uint32 values of sctp.SndRcvInfo structure

### ISSUE THREAD

**Issue by vildam** [ishidawataru/sctp#35]
Hello,
I tried to set PPID = 46 (value of DIAMETER)
```
info := &sctp.SndRcvInfo{
	Stream: uint16(ppid),
	PPID:   uint32(46),
}
```
This value of PPID encoded as 771751936 (BigIndian style), but *nativeEndian* value from init 
 function determined as binary.LittleEndian and all uint16 values of structure SndRcvInfo encoded correctly, issue only with uint32 values.

As a temporary solution, I set PPID = 771751936.

Thanks in advance!

**Comment by ishidawataru** [comment]
@vildam https://tools.ietf.org/html/rfc6458 Section 5.3.2

>   sinfo_ppid:  This value in sendmsg() is an unsigned integer that is
>      passed to the remote end in each user message.  In recvmsg(), this
>      value is the same information that was passed by the upper layer
>      in the peer application.  Please note that the SCTP stack performs
>      no byte order modification of this field.  For example, if the
>      DATA chunk has to contain a given value in network byte order, the
>      SCTP user has to perform the htonl() computation.

looks like PPID doesn't get translated to network byte order in `recvmsg()`.

Are you trying to connect with existing diameter implementation by using this library?

**Comment by vildam** [comment]
I used an implementation that does not set the PPID value in messages.
After that, I tried to set PPID value by your **example/sctp.go.**

I got your point,
Thanks!
