### ISSUE TITLE
Issue with the default value of Payload Protocol Identifier in SCTP layer

### ISSUE THREAD

**Issue by edkowalski** [ishidawataru/sctp#38]
Hello,
By default the Payload Protocol Identifier of the SCTP layer is set to 00. Could a function/constant be added so that users could overwrite this setting?
Thank you

**Comment by shanehooker** [comment]
You can override it by using the SetDefaultSentParam() API provided by the SCTPConn. You just need to ensure you set the value properly to be placed on the network by using LittleEndian.
```
const SCTP_PPID_NGAP  = 60

sctpPPID := binary.LittleEndian.Uint32([]byte{0, 0, 0, SCTP_PPID_NGAP})
// Set the default PPID for sent data packets to be 60 (NGAP)
err := conn.SetDefaultSentParam(&sctp.SndRcvInfo{PPID: sctpPPID})
```

**Comment by edkowalski** [comment]
I've added that code snippet to my script and now all works as I intended. Thank you very much!
