### ISSUE TITLE
failed to listen: cannot assign requested address

### ISSUE THREAD

**Issue by ProfCoinSoft** [ishidawataru/sctp#50]
I run this example (on Debian 10):

> $ cd example
> $ go build
> $ # run example SCTP server
> $ ./example -server -port 1000 -ip 10.10.0.1,10.20.0.1

and I received the error: **failed to listen: cannot assign requested address** at **sctp_linux.go** in **215 line**:

> err = SCTPBind(sock, laddr, SCTP_BINDX_ADD_ADDR)

I had to try to change port and IP, but this problem doesn't decide

Please help me resolve this problem! Thanks!

**Comment by ProfCoinSoft** [comment]
I could solved the problem. Need point real IP address for your network interfaces.

**Comment by tanishq-akula** [comment]
Hi @microup, 

I am facing the similar issue.
I am trying  this setup on ubuntu virtual box though.
When you say "point real IP address", do you mean IP address on host machine or IP address inside the VM. And does it  mean virtual IP based on virtual interface ?

Thanks in Advance.
